---
- include: packages.yml
# this is handled by a meta dependency on that role
#- include: ../../../roles/madek_servers/tasks/packages.yml
- include: locale.yml
- include: vim.yml
- include: ntp.yml

- name: Make sure jenkins user is present
  user: name=jenkins shell=/bin/bash state=present

# Need to improve below by storing those keys somewhere central.
- name: Install root SSH keys
  authorized_key: user=root key={{ item }} state=present
  with_file:
    - ../../../files/ssh_keys/rca.pub
    - ../../../files/ssh_keys/thomas.pub
    - ../../../files/ssh_keys/franco.pub
    - ../../../files/ssh_keys/sebastian.pub

- name: Install jenkins SSH keys
  authorized_key: user=jenkins key={{ item }} state=present
  with_file:
    - ../../../files/ssh_keys/rca.pub
    - ../../../files/ssh_keys/thomas.pub
    - ../../../files/ssh_keys/franco.pub
    - ../../../files/ssh_keys/sebastian.pub
    - ../../../files/ssh_keys/matus.pub

- include: postgresql.yml

- name: Set default Ruby
  sudo: True
  sudo_user: jenkins
  command: executable=/bin/bash bash -l -c '{{set_default_ruby_command}} {{ default_ruby_version }}'
  when: rbenv_is_installed|success

- name: Install cleanup cronjob
  copy: src=jenkins_cleanup dest=/etc/cron.weekly/jenkins_cleanup mode=755
