---
- include: iceweasel.yml
- include: packages.yml
- include: locale.yml
- include: vim.yml
- include: ntp.yml

- name: Create jenkins user
  user: name=jenkins shell=/bin/bash state=present

# Need to improve below by storing those keys somewhere central.
- name: Install root SSH keys
  authorized_key: user=root key={{ item }} state=present
  with_file:
    - ../../../files/ssh_keys/rca.pub
    - ../../../files/ssh_keys/thomas.pub
    - ../../../files/ssh_keys/franco.pub
    - ../../../files/ssh_keys/sebastian.pub

- name: Install jenkins SSH keys
  authorized_key: user=jenkins key={{ item }} state=present
  with_file:
    - ../../../files/ssh_keys/rca.pub
    - ../../../files/ssh_keys/thomas.pub
    - ../../../files/ssh_keys/franco.pub
    - ../../../files/ssh_keys/sebastian.pub
    - ../../../files/ssh_keys/matus.pub

- include: chromedriver.yml
- include: phantomjs.yml
- include: postgresql.yml

- name: Set default Ruby 
  command: executable=/bin/bash bash -l -c 'rbenv global 1.9.3-p448'
  when: rbenv_is_installed|success
