---
- name: Install VNC server
  apt: pkg=tightvncserver state=installed update_cache=true
- name: Install Fluxbox
  apt: pkg=fluxbox state=installed update_cache=true
- name: Install xbase-clients
  apt: pkg=xbase-clients state=installed update_cache=true
- name: Install Java (OpenJDK)
  apt: pkg=openjdk-7-jre state=installed
- name: Install unzip
  apt: pkg=unzip state=installed
- name: Install zip
  apt: pkg=zip state=installed
- name: Install Chromium
  apt: pkg=chromium state=installed
- name: Install Curl
  apt: pkg=curl state=installed
