---
- name: Install PostgreSQL
  apt: pkg={{ item }} state=present
  with_items:
    - postgresql
    - postgresql-client
    - libpq-dev
    - postgresql-contrib
    - python-psycopg2
- name: Give the root user a PostgreSQL superuser so the rest of these steps work
  command: su postgres -c 'createuser -rsd root'
  ignore_errors: True

- name: Switch off PostgreSQL security
  copy: src=pg_hba_no_security.conf dest=/etc/postgresql/9.1/main/pg_hba.conf
  notify:
    - restart postgresql

- name: Create jenkins PostgreSQL user
  postgresql_user: name=jenkins password=jenkins
#  sudo: True
#  sudo_user: postgres

- name: Enable PostgreSQL Trigram extension
  shell: psql template1 -c 'CREATE EXTENSION pg_trgm;'
  ignore_errors: True
#  sudo: True
#  sudo_user: postgres

- name: Give jenkins a PostgreSQL database
  postgresql_db: name=jenkins owner=jenkins state=present
#  sudo: True
#  sudo_user: postgres
