---
- name: Install packages for rbenv
  apt: pkg={{ item }} state=present
  with_items:
    - git
    - libreadline-dev
    - libreadline6-dev
    - libssl-dev
    - libxslt1-dev
    - libxml2-dev
    - build-essential
    - zlib1g-dev
    - openjdk-7-jre
- name: Check if rbenv is installed
  command: ls {{ rbenv_root }} 
  register: rbenv_is_installed
  ignore_errors: True
- name: Install rbenv globally
  git: repo=https://github.com/sstephenson/rbenv.git dest={{ rbenv_root }}
  when: rbenv_is_installed|failed
- name: Install ruby-build so you can install Rubies through rbenv
  git: repo=https://github.com/sstephenson/ruby-build.git dest={{ rbenv_root }}/plugins/ruby-build
  when: rbenv_is_installed|failed
- name: Install rbenv profile snippet
  template: src=rbenv.sh.j2 dest=/etc/profile.d/rbenv.sh
  when: rbenv_is_installed|failed
- name: Check if Ruby is installed
  command: bash -l -c 'rbenv versions | grep {{ ruby_version }}'
  register: ruby_is_installed
  ignore_errors: True
- name: Install rbenv Ruby
  command: executable=/bin/bash bash -l -c 'rbenv install {{ ruby_version }}'
  when: rbenv_is_installed|success and ruby_is_installed|failed
  register: ruby_has_been_installed
