---
- include: packages.yml
# this is handled by a meta dependency on that role
#- include: ../../../roles/madek_servers/tasks/packages.yml
- include: vim.yml

- name: Make sure jenkins user is present
  user: name=jenkins shell=/bin/bash state=present

- name: Set default Ruby
  sudo: True
  sudo_user: jenkins
  command: chdir={{ rbenv_root.stdout }} executable=/bin/bash bash -l -c 'RBENV_ROOT={{ rbenv_root.stdout }} rbenv global {{ default_ruby_version }}'
  when: rbenv_is_installed|success

- name: Install cleanup cronjob
  copy: src=jenkins_cleanup dest=/etc/cron.weekly/jenkins_cleanup mode=755
