---
- name: Install Ruby compilation dependencies
  apt: pkg={{ item }} state=present
  with_items:
    - build-essential
    - curl
    - bash
  tags:
    - packages

- name: Install a JRE if jRuby needs to be installed
  apt: pkg=openjdk-7-jre state=present
  when: ruby_version[:5] == "jruby"
