# All authorization, but especially root stuff, should be handled from
# this file and not in any of the roles. Otherwise the roles become
# less reusable.
---
- hosts: ci2.zhdk.ch
  tasks:
  - name: Authorize root users for ci2.zhdk.ch
    authorized_key: user=root key={{ item }} state=present
    with_file:
      - files/ssh_keys/rca.pub
      - files/ssh_keys/thomas.pub

- hosts: ci.zhdk.ch
  tasks:
  - name: Root users for ci.zhdk.ch
    authorized_key: user=root key={{ item }} state=present
    with_file:
      - files/ssh_keys/rca.pub
