---
- hosts: developer_vm_leihs
  roles:
    - servers/developer_vm_leihs
    - servers/mariadb
    - iceweasel_latest
    - binaries/chromedriver
    - binaries/phantomjs
    - servers/rails
    - { role: ruby/rvm_gherkin_lexer_hack, ruby_version: 1.9.3-p448 }
