---
- hosts: developer_vm_madek
  user: developer
  sudo: True
  roles:
    - servers/mariadb
    - iceweasel_latest
    - chromedriver
    - phantomjs
    - servers/rails
    - rvm_gherkin_lexer_hack
    - remote_display
  tasks:
    - include: roles/servers/madek/tasks/packages.yml
    - include: tasks/developer_vm_madek_virtual_host.yml
  handlers:
    - include: roles/servers/web/handlers/main.yml
