---
- hosts: developer_vm_madek
  roles:
    - servers/developer_vm_madek
    - servers/mariadb
    - iceweasel_latest
    - chromedriver
    - phantomjs
    - servers/rails
    - rvm_gherkin_lexer_hack
  handlers:
    - include: roles/servers/web/handlers/main.yml
