---
- hosts: developer_vm_madek
  roles:
    - servers/developer_vm_madek
    - servers/mariadb
    - iceweasel_latest
    - binaries/chromedriver
    - binaries/phantomjs
    - servers/rails
    - ruby/rvm_gherkin_lexer_hack
