---
- hosts: madek_servers
  roles:
    - madek_servers
  handlers:
    - include: roles/webservers/handlers/main.yml


- hosts: 192.168.56.102
  tasks:
    - include: roles/madek_servers/tasks/madek_vagrant_virtual_host.yml
    - name: Give madek a PostgreSQL user
      sudo_user: postgres
      sudo: True
      postgresql_user: name=madek password=madek state=present
    - name: Give madek a PostgreSQL database
      sudo_user: postgres
      sudo: True
      postgresql_db: name=madek owner=madek state=present
  handlers:
    - include: roles/webservers/handlers/main.yml
