---
- name: Check if RVM is installed
  command: rvm --version
  register: rvm_is_installed
  ignore_errors: True

- name: Install RVM
  shell: curl -L https://get.rvm.io | bash -s stable
  register: rvm_has_been_installed
  when: rvm_is_installed|failed

- name: Install Ruby
  command: bash -l -c 'rvm install 1.9.3'
  register: ruby_has_been_installed
  when: rvm_is_installed|success

- name: Install Ruby
  command: bash -l -c 'rvm install 1.9.3'
  register: ruby_installed
  when: rvm_has_been_installed|success

- name: Set default Ruby
  command: bash -l -c 'rvm alias create default 1.9.3'
  when: ruby_installed|success
