---
- name: Install PhantomJS dependencies 
  apt: pkg={{ item }} state=installed
  with_items:
    - curl
    - bzip2
- name: Download PhantomJS
  shell: curl https://phantomjs.googlecode.com/files/phantomjs-1.9.0-linux-{{ ansible_machine }}.tar.bz2 | tar xj chdir=/tmp
- name: Stick PhantomJS somewhere in the PATH
  command: cp phantomjs-1.9.0-linux-{{ ansible_machine }}/bin/phantomjs /usr/local/bin/ chdir=/tmp
- name: Change mode of PhantomJS to be executable
  file: path=/usr/local/bin/phantomjs mode=755
