---
- name: Install PostgreSQL
  apt: pkg={{ item }} state=present
  with_items:
    - postgresql
    - postgresql-client
    - libpq-dev
    - postgresql-contrib
    - python-psycopg2
- name: Give the root user a PostgreSQL superuser so the rest of these steps work
  command: su postgres -c 'createuser -rsd root'
  ignore_errors: True
- name: Enable PostgreSQL Trigram extension
  shell: psql template1 -c 'CREATE EXTENSION pg_trgm;'
  ignore_errors: True
