---
- name: restart postgresql
  service: name=postgresql state=restarted
- name: reload postgresql
  service: name=postgresql state=reloaded
- name: restart apache
  service: name=apache2 state=restarted
