---
dependencies:
  - { role: common }
  - { role: configuration/utf8_locale }
  - { role: servers/postgresql, enable_trigram: true }
  - { role: ntp_client }
  - { role: remote_display }
  - { role: binaries/chromedriver }
  - { role: binaries/phantomjs }
  - { role: iceweasel_latest }
  - { role: ruby/rbenv_ruby, ruby_version: 1.9.3-p448, ruby_user: jenkins, set_default: true }
  - { role: ruby/rbenv_ruby, ruby_version: jruby-1.7.2, ruby_user: jenkins }
  - { role: ruby/rbenv_gherkin_lexer_hack, ruby_version: 1.9.3-p448}
  - { role: servers/domina_ci_executor, dest: /home/domina/domina_ci_executor, user: domina }
